CC=g++
Vector:
	$(CC) -o Vector VectorApdorojimas.cpp funkcijos.cpp
Deque: 
	$(CC) -o Deque DeQueApdorojimas.cpp Dequefunkcijos.cpp
List:
	$(CC) -o List ListApdorojimas.cpp Listfunkcijos.cpp
GenerateFile:
	$(CC) -o GenerateFile SarasoGen.cpp
clean:
	rm *. *.txt
